# Generated by Django 5.1.6 on 2025-10-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_contact_conversation_assigned_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Internal messages between staff members'),
        ),
    ]
