# Generated by Django 5.1.6 on 2025-10-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_message_is_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
